config/routes.rb
Hug::Application.routes.draw do
  resources :charges
  resources :subscribers
  resources :sessions, only: [:new, :create, :destroy]

  get '/', to: 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  match '/create', to: 'subscribers#new',  via: 'get'
  match '/login', to: 'sessions#new',      via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }

	has_secure_password
  has_many :charges

  validates :password, length: { minimum: 6 }
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :first_name && :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  def Subscriber.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Subscriber.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = Subscriber.encrypt(Subscriber.new_remember_token)
    end
	has_secure_password
	has_many :charges


	def self.stripe_customer_creator

	    # Set your secret key: remember to change this to your live secret key in production
	    # See your keys here https://manage.stripe.com/account

    	# Get the credit card details submitted by the form
    token = params[:stripeToken]


   	 # Create a Customer
    customer = Stripe::Customer.create(
      :card => token,
      :description => "payinguser@example.com"
    )
   	 #set params to include the returned customer id from stripe
    params[:subscriber][:stripe_customer_id] = customer.id

    @subscriber = Subscriber.new(subscriber_params)
      if @subscriber.save
        redirect_to @subscriber, notice: 'Subscriber was successfully created.'
      else
        render action: 'new'
      end
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create

    # Get the credit card details submitted by the form
    token = params[:stripeToken]


    # Create a Customer
    customer = Stripe::Customer.create(
      :card => token,
      :description => params[:subscriber][:email]
    )
    #set params to include the returned customer id from stripe
    params[:subscriber][:stripe_customer_id] = customer.id

    @subscriber = Subscriber.new(subscriber_params)
      if @subscriber.save
        redirect_to @subscriber, notice: 'Subscriber was successfully created.'
      else
        render 'new'
      end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:password, :password_confirmation, :email, :first_name, :last_name, :phone, :billing_address, :billing_city, :billing_state, :billing_zip, :ship_date, :password_digest, :stripe_customer_id, :payment_status, :recipient_name, :recipient_address, :recipient_city, :recipient_state, :recipient_zip)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<div class="span6 offset3 create_form">
  <h1>Welcome New Friend</h1>
  <%= form_for(@subscriber) do |f| %>
    <% if @subscriber.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

        <ul>
        <% @subscriber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h3>Personal Info</h3>
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>

    <h3>Payment Information</h3>

    <div class="field">
      <%= f.label :billing_address %><br>
      <%= f.text_field :billing_address %>
    </div>
    <div class="field">
      <%= f.label :billing_city %><br>
      <%= f.text_field :billing_city %>
    </div>
    <div class="field">
      <%= f.label :billing_state %><br>
      <%= f.text_field :billing_state %>
    </div>
    <div class="field">
      <%= f.label :billing_zip %><br>
      <%= f.text_field :billing_zip %>
    </div>
    <div class="field">
      <%= f.label :ship_date %><br>
      <%= f.date_select :ship_date %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>

    <h3> Who will be recieving this Hug? </h3>

    <div class="field">
      <%= f.label :recipient_name %><br>
      <%= f.text_field :recipient_name %>
    </div>
    <div class="field">
      <%= f.label :recipient_address %><br>
      <%= f.text_field :recipient_address %>
    </div>
    <div class="field">
      <%= f.label :recipient_city %><br>
      <%= f.text_field :recipient_city %>
    </div>
    <div class="field">
      <%= f.label :recipient_state %><br>
      <%= f.text_field :recipient_state %>
    </div>
    <div class="field">
      <%= f.label :recipient_zip %><br>
      <%= f.text_field :recipient_zip %>
    </div>

    <h3>Stripe Information (will be sent to you in EMAIL)!</h3>

    <div class="field">
      <%= f.label :stripe_customer_id %><br>
      <%= f.text_field :stripe_customer_id %>
    </div>
    <div class="field">
      <%= f.label :payment_status %><br>
      <%= f.text_field :payment_status %>
    </div>

  <form action="" method="POST">
    <script
      src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
      data-key="pk_bGm2m7m1iQwdDpppL3b2sVdYPnW9Y"
      data-amount="2000"
      data-name="Demo Site"
      data-description="2 widgets ($20.00)"
      data-image="">
    </script>
    <br/>
    <br/>
    <%= link_to "Back", '/', class: 'btn btn-small' %>
  </form>
  <% end %>
</div>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render '/layouts/form' %>
<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Phone</th>
      <th>Billing address</th>
      <th>Billing city</th>
      <th>Billing state</th>
      <th>Billing zip</th>
      <th>Processor token</th>
      <th>Ship date</th>
      <th>Password digest</th>
      <th>Stripe customer</th>
      <th>Payment status</th>
      <th>Recipient name</th>
      <th>Recipient address</th>
      <th>Recipient city</th>
      <th>Recipient state</th>
      <th>Recipient zip</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.first_name %></td>
        <td><%= subscriber.last_name %></td>
        <td><%= subscriber.phone %></td>
        <td><%= subscriber.billing_address %></td>
        <td><%= subscriber.billing_city %></td>
        <td><%= subscriber.billing_state %></td>
        <td><%= subscriber.billing_zip %></td>
        <td><%= subscriber.processor_token %></td>
        <td><%= subscriber.ship_date %></td>
        <td><%= subscriber.password_digest %></td>
        <td><%= subscriber.stripe_customer_id %></td>
        <td><%= subscriber.payment_status %></td>
        <td><%= subscriber.recipient_name %></td>
        <td><%= subscriber.recipient_address %></td>
        <td><%= subscriber.recipient_city %></td>
        <td><%= subscriber.recipient_state %></td>
        <td><%= subscriber.recipient_zip %></td>
        <td><%= subscriber.password %></td>
        <td><%= subscriber.password_confirmation %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<%= render 'form' %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @subscriber.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @subscriber.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @subscriber.phone %>
  <strong>Phone:</strong>
  <%= @subscriber.phone %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @subscriber.billing_address %>
</p>

<p>
  <strong>Billing city:</strong>
  <%= @subscriber.billing_city %>
</p>

<p>
  <strong>Billing state:</strong>
  <%= @subscriber.billing_state %>
</p>

<p>
  <strong>Billing zip:</strong>
  <%= @subscriber.billing_zip %>
</p>

<p>
  <strong>Processor token:</strong>
  <%= @subscriber.processor_token %>
  <strong>Ship date:</strong>
  <%= @subscriber.ship_date %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @subscriber.payment_status %>
</p>

<p>
  <strong>Recipient name:</strong>
  <%= @subscriber.recipient_name %>
</p>

<p>
  <strong>Recipient address:</strong>
  <%= @subscriber.recipient_address %>
</p>

<p>
  <strong>Recipient city:</strong>
  <%= @subscriber.recipient_city %>
</p>

<p>
  <strong>Recipient state:</strong>
  <%= @subscriber.recipient_state %>
</p>

<p>
  <strong>Recipient zip:</strong>
  <%= @subscriber.recipient_zip %>
</p>

<p>
  <strong>Password:</strong>
  <%= @subscriber.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @subscriber.password_confirmation %>
</p>


<form action="" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>

<h4>Recent Transactions:</h4>
<%= @subscriber.charges.each do  |charge| %>
  <div class="well">
    <p><h4>Charge</h4></p>
    Credit Card Last 4: <%= charge.last_4 %> ----
    Payment Status: <%= charge.paid_status %> ----
    Payment Created: <%= charge.created_at %>
  </div>
<% end %>