config/routes.rb
Hug::Application.routes.draw do
  resources :charges
  resources :subscribers
  resources :sessions, only: [:new, :create, :destroy]

  get '/', to: 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  match '/create', to: 'subscribers#new',  via: 'get'
  match '/login', to: 'sessions#new',      via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
	belongs_to :subscriber

	def self.charge_machine

    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://manage.stripe.com/account
    Stripe.api_key = "sk_k4XKAXwn5PpyQmLM3ChOKR4ncHfCh"

    @subscribers = Subscriber.where(ship_date: Date.today)

    @subscribers.each do |s|

        # charge customer from customer id and then pass the return "hash" into current charge variable
      current_charge = Stripe::Charge.create(
      :amount   => 598,
      :currency => "usd",
      :customer => s.stripe_customer_id
      )

       # get values from returned hash and assign them to corresponding locations in database
      s.payment_status = current_charge.paid
      last_4 = current_charge.card.last4
      charge_token = current_charge.id
      s.save
        #add values to charge-params from @subscriber & stripe return
      @charge = Charge.new(paid_status: current_charge.paid, last_4: last_4, stripe_token: charge_token, subscriber_id: s.id)
        if @charge.save
         	#s.payment_status = "good"
          puts "success and other stuff"
        else
          puts "HUUUUUGGGGEEEEE PPRRRRROOOOBBBBLLLLEEMMM"
        end
    end
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charge }
      else
        format.html { render action: 'new' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:paid_status, :stripe_token, :last_4, :subscriber_id)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paid_status %><br>
    <%= f.text_field :paid_status %>
  </div>
  <div class="field">
    <%= f.label :stripe_token %><br>
    <%= f.text_field :stripe_token %>
  </div>
  <div class="field">
    <%= f.label :last_4 %><br>
    <%= f.text_field :last_4 %>
  </div>
  <div class="field">
    <%= f.label :subscriber_id %><br>
    <%= f.number_field :subscriber_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<table>
  <thead>
    <tr>
      <th>Paid status</th>
      <th>Stripe token</th>
      <th>Last 4</th>
      <th>Subscriber</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.paid_status %></td>
        <td><%= charge.stripe_token %></td>
        <td><%= charge.last_4 %></td>
        <td><%= charge.subscriber_id %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paid status:</strong>
  <%= @charge.paid_status %>
</p>

<p>
  <strong>Stripe token:</strong>
  <%= @charge.stripe_token %>
</p>

<p>
  <strong>Last 4:</strong>
  <%= @charge.last_4 %>
</p>

<p>
  <strong>Subscriber:</strong>
  <%= @charge.subscriber_id %>
</p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>