config/routes.rb
Hug::Application.routes.draw do
  resources :charges
  resources :subscribers
  resources :sessions, only: [:new, :create, :destroy]

  get '/', to: 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/faq', to: 'static_pages#faq'
  match '/create', to: 'subscribers#new',  via: 'get'
  match '/login', to: 'sessions#new',      via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_dig_bar.html.erb
<div class="digwrapper">
  <script type='text/javascript' src='http://w.sharethis.com/button/buttons.js?ver=3.5.2'></script>

  <!-- Pintrist -->
    <span class='st_pinterest_vcount' style="margin-bottom: 10px;
    display: block;
    margin-left: -7px;" displayText='Pinterest' st_url="http://28dayhug.com/" st_title="28 day hug!"
    st_image="assets/img/my28dayg.jpg" st_summary="www.28dayhug.com - After a long day at work coming home to some nice tea, really good chocolate, and taking a nice long shower with aromatherapy steam wrapping around you...that's the way to melt away all the stress and ease the tension of your monthly visitor."></span>

  <!-- Google+ -->
  <script type='text/javascript' src='https://apis.google.com/js/plusone.js'></script><g:plusone size='tall' href='http://28dayhug.com/'></g:plusone>

  <!-- Stumbleupon -->
    <!-- Place this tag where you want the su badge to render -->
  <su:badge layout="5"></su:badge>

  <!-- Place this snippet wherever appropriate -->
  <script type="text/javascript">
    (function() {
      var li = document.createElement('script'); li.type = 'text/javascript'; li.async = true;
      li.src = ('https' == document.location.protocol ? 'https:' : 'http:') + '//platform.stumbleupon.com/1/widgets.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(li, s);
    })();
  </script>

  <!-- REDDIT -->
    <iframe src="http://www.reddit.com/static/button/button2.html?width=51&url=http%3A%2F%2F28dayhug.com%2F&title=Home&newwindow='1'" height="69" width="51" scrolling='no' frameborder='0'></iframe>
</div>

app/views/layouts/_footer.html.erb
<div class="footerwrapper">
  <div class="footerinner">
    <h3> Thanks for visiting!</h3>
    <br/>
    <span class="copyright"> © 2011 Lovely Brands LLC All Rights Reserved </span>
  </div>
</div>

app/views/layouts/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :billing_address %><br>
    <%= f.text_field :billing_address %>
  </div>
  <div class="field">
    <%= f.label :billing_city %><br>
    <%= f.text_field :billing_city %>
  </div>
  <div class="field">
    <%= f.label :billing_state %><br>
    <%= f.text_field :billing_state %>
  </div>
  <div class="field">
    <%= f.label :billing_zip %><br>
    <%= f.number_field :billing_zip %>
  </div>
  <div class="field">
    <%= f.label :processor_token %><br>
    <%= f.text_field :processor_token %>
  </div>
  <div class="field">
    <%= f.label :recipient_name %><br>
    <%= f.text_field :recipient_name %>
  </div>
  <div class="field">
    <%= f.label :recipient_address %><br>
    <%= f.text_field :recipient_address %>
  </div>
  <div class="field">
    <%= f.label :recipient_city %><br>
    <%= f.text_field :recipient_city %>
  </div>
  <div class="field">
    <%= f.label :recipient_state %><br>
    <%= f.text_field :recipient_state %>
  </div>
  <div class="field">
    <%= f.label :recipient_zip %><br>
    <%= f.number_field :recipient_zip %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="headerinner">
    <div class="logoholder">
      <div class="logoitem twentyheader">
        <a href="/" title="28dayhug">
        <%= link_to image_tag("28-logo-top.png", alt: "28 day hug", class: "headerlogo") %>
        </a>
      </div>
    </div>

  <div class="sharewrapper">
    <div id="mc_embed_signup">
    </div>
    <div class="headersocialwrap">
      <div class="topheadshare">Find Us On
        <%= image_tag("arrow_top.png", alt: "28 day hug", class: "headsharelogo") %>
      </div>

      <div class="headershareitem">
        <a href="https://www.facebook.com/28dayhug" target="_blank" class="socialtop facebooktop"></a>
      </div>

      <div class="headershareitem">
        <a href="https://twitter.com/28dayhug" target="_blank" class="socialtop twittertop"></a>
      </div>

      <div class="headershareitem">
        <a href="http://pinterest.com/28dayhug/"target="_blank"class="socialtop pinteresttop"></a>
      </div>
    </div>
      <a href="#" class="contactheader">Help Desk & FAQ</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>28 Day Hug</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header class="navbar">
      <div class="navbar-inner">
        <!-- navbar container -->
        <div class="container-fluid">
          <div class="row-fluid">
            <%= link_to image_tag("28-logo-top.png", alt: "28 day hug", class: "headerlogo"), '/' %>
            <div class="socialbtns pull-right">
              <%= link_to image_tag("socialbuttonsfbook.png", alt: "facebook logo/link", class:"headersocialnav"),'https://www.facebook.com/28dayhug'%>
              <%= link_to image_tag("socialbuttonstwit.png", alt:"twitter logo/link", class:"headersocialnav"),'https://twitter.com/28dayhug'%>
              <%= link_to image_tag("socialbuttonspint.png", alt:"pintrist logo/link", class:"headersocialnav"),'http://pinterest.com/28dayhug/'%>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- <div class="span1"> -->
      <!-- < render "layouts/dig_bar" %> -->
    <!-- </div> -->


    <div class="container-fluid">
      <div class="row-fluid">
        <%= link_to "Log in", login_path, class: "login btn btn-normal pull-right" %>
        <%= link_to "Create Account", create_path, class: "login btn btn-normal pull-right" %>
        <!-- <a href="#"class="user-btn pull-right">Log In</a> -->
      </div>

      <div class='row-fluid'>
        <div class="span12">

          <%= yield %>
        </div>
      </div>

      <div class="row-fluid">
        <div class="footerwrapper">
          <div class="footerinner">
            <h3> Thanks for visiting!</h3>
            <br/>
            <a href="/faq" class="contactheader">Help Desk & FAQ</a>
            <br/>
            <span class="copyright"> © 2011 Lovely Brands LLC All Rights Reserved </span>
          </div>
        </div>
      </div>
    </div>


</body>
</html>

app/views/layouts/navbar_mock.html.erb
<header class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("28-logo-top.png", alt: "28 day hug", class: "headerlogo"), '/' %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to image_tag("socialbuttonsfbook.png", alt: "facebook logo/link", class:"headersocialnav"),'https://www.facebook.com/28dayhug'%></li>
          <li><%= link_to image_tag("socialbuttonstwit.png", alt:"twitter logo/link", class:"headersocialnav"),'https://twitter.com/28dayhug'%></li>
          <li><%= link_to image_tag("socialbuttonspint.png", alt:"pintrist logo/link", class:"headersocialnav"),'http://pinterest.com/28dayhug/'%></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

<div id="header">
      <div class="headerinner">
        <div class="logoholder twentyheader">
          <div class="logoitem">
            <%= link_to image_tag("28-logo-top.png", alt: "28 day hug", class: "headerlogo"), '/' %>
          </div>
        </div>
        <div class="sharewrapper">
          <div id="mc_embed_signup">
            <!-- Info for mailing list -->
          </div>
          <div class="headersocialwrap">
            <div class="topheadshare">Find Us On
              <%= link_to image_tag("arrow_top.png", alt: "social pointer", class: "headsharelogo") %>
            </div>

            <div class="headershareitem">
              <a href="https://www.facebook.com/28dayhug" target="_blank" class="socialtop facebooktop"></a>
            </div>

            <div class="headershareitem">
              <a href="https://twitter.com/28dayhug" target="_blank" class="socialtop twittertop"></a>
            </div>

            <div class="headershareitem">
              <a href="http://pinterest.com/28dayhug/"target="_blank"class="socialtop pinteresttop"></a>
            </div>
          </div>
        </div>
      </div>
    </div>